spring.application.name=authService

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/planning_db
spring.datasource.username=aejimenez
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=EstaEsUnaClaveSecretaParaJWT
jwt.expiration=86400000