spring.application.name=taskService

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/planning_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aejimenez}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true