spring.application.name=taskService

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/planning_db
spring.datasource.username=aejimenez
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true